version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: zenithtrader_db
    environment:
      POSTGRES_DB: zenith_trader_db
      POSTGRES_USER: zenith_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    ports:
      - "5432:5432"
    networks:
      - zenith_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zenith_user -d zenith_trader_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: zenithtrader_redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - zenith_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # Zenith Trader Application
  app:
    image: lprnmns/zenith-trader:latest
    container_name: zenithtrader_app
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: postgresql://zenith_user:${POSTGRES_PASSWORD}@postgres:5432/zenith_trader_db
      REDIS_URL: redis://redis:6379
      
      # Security
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      JWT_SECRET: ${JWT_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
      
      # External APIs
      ZERION_API_KEY: ${ZERION_API_KEY}
      ETHERSCAN_API_KEY: ${ETHERSCAN_API_KEY}
      OKX_API_KEY: ${OKX_API_KEY}
      OKX_API_SECRET: ${OKX_API_SECRET}
      OKX_PASSPHRASE: ${OKX_PASSPHRASE}
      OKX_DEMO_MODE: 0
      
      # Notifications
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
      VAPID_CONTACT_EMAIL: admin@zenithtrader.com
      
      # Google OAuth
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: https://zenithtrader.alperenmanas.app/api/auth/google/callback
      GOOGLE_SUCCESS_REDIRECT: https://zenithtrader.alperenmanas.app/auth/success  
      GOOGLE_FAILURE_REDIRECT: https://zenithtrader.alperenmanas.app/auth/error
      
      # Email
      GMAIL_USER: ${GMAIL_USER}
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}
      
      # CORS
      FRONTEND_URL: https://zenithtrader.alperenmanas.app
      CORS_ORIGIN: https://zenithtrader.alperenmanas.app

    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - zenith_network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: zenithtrader_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - app
    networks:
      - zenith_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  zenith_network:
    driver: bridge
